import _Library._ProjectConstant._Constant_Data as const

RAW_DATA_FILE_PREFIX = './data/'

FILE_EXTNAME = '.txt'
FILE_ID = '25ic'

EXPORT_FILE_PREFIX_Y = 'Y_'
EXPORT_FILE_PREFIX_X = 'X_'
EXPORT_FILE_PREFIX_NOMR = '_NORM'
EXPORT_FILE_PREFIX_NORM_SPEC = 'SPEC_'
EXPORT_FILE_PREFIX_NORM_CFR = 'CFR_'

X_DATA_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + EXPORT_FILE_PREFIX_X + FILE_ID + FILE_EXTNAME
Y_DATA_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + EXPORT_FILE_PREFIX_Y + FILE_ID + FILE_EXTNAME
# # Train set, Test set 參數
X_TRAIN_SET_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + 'X_train_set_' + FILE_ID + '.csv'
Y_TRAIN_SET_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + 'Y_train_set_' + FILE_ID + '.csv'
X_TEST_SET_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + 'X_test_set_' + FILE_ID + '.csv'
Y_TEST_SET_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + 'Y_test_set_' + FILE_ID + '.csv'
print("X_DATA_PATH: ", X_DATA_PATH)
print("Y_DATA_PATH: ", Y_DATA_PATH)
print("X_TRAIN_SET_PATH: ", X_TRAIN_SET_PATH)
print("Y_TRAIN_SET_PATH: ", Y_TRAIN_SET_PATH)
print("X_TEST_SET_PATH: ", X_TEST_SET_PATH)
print("Y_TEST_SET_PATH: ", Y_TEST_SET_PATH)

# # Normalizer 參數
NORMALIZE_SCALER_OBJ_FILE_NAME = 'SCALER_'
NORMALIZE_SCALER_OBJ_FILE_EXTNAME = '.pkl'
# Scaler的命名應該以實際關係來命名，而不是以x, y
NORMALIZE_SCALER_OBJ_DUMP_PATH_SPEC = const.Data.DATA_RESULT_SCALER_FOLDER + NORMALIZE_SCALER_OBJ_FILE_NAME + EXPORT_FILE_PREFIX_NORM_SPEC + FILE_ID + NORMALIZE_SCALER_OBJ_FILE_EXTNAME
NORMALIZE_SCALER_OBJ_DUMP_PATH_CFR = const.Data.DATA_RESULT_SCALER_FOLDER + NORMALIZE_SCALER_OBJ_FILE_NAME + EXPORT_FILE_PREFIX_NORM_CFR + FILE_ID + NORMALIZE_SCALER_OBJ_FILE_EXTNAME

print("NORMALIZE_SCALER_OBJ_DUMP_PATH_SPEC: ", NORMALIZE_SCALER_OBJ_DUMP_PATH_SPEC)
print("NORMALIZE_SCALER_OBJ_DUMP_PATH_CFR: ", NORMALIZE_SCALER_OBJ_DUMP_PATH_CFR)

X_DATA_NORM_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + EXPORT_FILE_PREFIX_X + FILE_ID + EXPORT_FILE_PREFIX_NOMR + FILE_EXTNAME
Y_DATA_NORM_PATH = const.Data.DATA_RESULT_OUTPUT_FOLDER + EXPORT_FILE_PREFIX_Y + FILE_ID + EXPORT_FILE_PREFIX_NOMR + FILE_EXTNAME

print("X_DATA_NORM_PATH: ", X_DATA_NORM_PATH)
print("Y_DATA_NORM_PATH: ", Y_DATA_NORM_PATH)
